### ISSUE TITLE
Dynamic to static link

### ISSUE THREAD

**Issue by PerMalmberg** [deplinenoise/tundra#274]
Perhaps I'm just overlooking something, but how do change an _ExternalLibrary_ that dynamically links against a .dylib (OS X) to to something that statically links agains the corresponding .a file of the same library?

**Comment by deplinenoise** [comment]
Can you share the `ExternalLibrary` declaration you're using currently?

**Comment by PerMalmberg** [comment]
This is it. What I want is to statically link to curl.

`ExternalLibrary {
	Name = "curl_osx",
	Pass = "Core",
	Propagate = {
		Env = {
			CPPDEFS = {
				"CORE_CURL=1",
			},
			LIBS = {
				"curl", 
				"crypto",
			},
		},	
	},
}`

**Comment by deplinenoise** [comment]
OK. The `LIBS` propagate will amounts to just adding `-lcurl` on the command line, I think. I assume there's a curl `.dylib` and a curl `.a` hanging out at the same location? How do you tell the OS X linker to pick one or the other? It seems it prefers the dynamic one.

**Comment by PerMalmberg** [comment]
I don't know, thats why I'm asking. What is needed, if I understand this correctly, is to explicitly specify the .a on the commandline to the linker and the headers to the compiler. The headers seems to be doable via a souces-directive, but I cannot get the .a to the linker commandline. Of course, my assumptions are based on that ld works similar as VS' linker..

**Comment by PerMalmberg** [comment]
That is, I don't know how to specify the .a as a commandline in the Tundra script. All info I've read seems to say that that is the way to go.

**Comment by deplinenoise** [comment]
Tundra will simply add `-l` in front of whatever is in the `LIBS` variable, if you're using gcc or clang. Here's the expansion is uses when linking a program, for example:

```lua
"$(LD) $(PROGOPTS) $(LIBPATH:p-L) -o $(@) $(<) $(LIBS:p-l)"
```

So if you want `-lfoo.a` you'd add `foo.a` to your `LIBS` instead of just `foo`. If you want to alternate that based on build configuration you can apply config filtering to the value as described in the docs.

**Comment by leidegre** [comment]
@PerMalmberg if you're looking for a quick way to test if you're on the right path you can go into the tools scripts folder and just change the command-line for linker invocation to whatever you want. I think, you can even override the LD command itself because it's just another environment variable nothing special about it. You could set `PROGOPTS` specifically for the unit you want to test with and then see if that works out as intended by invoking tundra with the verbose option to inspect the generated command lines.

**Comment by PerMalmberg** [comment]
Thanks, I'll dig deeper into this next week.

**Comment by PerMalmberg** [comment]
this turned out to be fairly easy, just specify the .a-file in PROGOPTS. Building cURL for OS X 10.7 was another matter but it's all working now. :)

**Comment by leidegre** [comment]
@PerMalmberg excellent, happy to help :)
