### ISSUE TITLE
v2.0 release binary for windows missing

### ISSUE THREAD

**Issue by dyu** [deplinenoise/tundra#288]
https://github.com/deplinenoise/tundra/commit/469c9bfc3f1ff4b855f172cd874d0740734f292a

I was able to compile ok on ubuntu.  Tundra is really fast.

I was getting errors crosscompiling it for windows hence the request for the binary :-)

**Comment by deplinenoise** [comment]
My crosscompile env is a little shot at the moment. Is there a reason you can't build it yourself on Windows using Visual Studio?

**Comment by dyu** [comment]
I've never used visual studio except for their command line tools from http://landinghub.visualstudio.com/visual-cpp-build-tools

I tried to execute ```msbuild Tundra.sln``` but that didn't work.

**Comment by leidegre** [comment]
I recently did this and it was a little bit of pain but once I found the right _packages_ it built just fine.

You can use the msys2 environment on Windows and then download the tool chain from here https://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.0/64-bit/threads-win32/seh/

Unzip that, add `x86_64-w64-mingw32\bin` to your path and configure the environment for the windows build, then run make.

I'm using VS2015 right now and it's giving my build errors as well but I think this is just because it's looking for the wrong version of the VC++ compiler. We can override this like so:

> msbuild /p:PlatformToolset=v140;Configuration=Release vs2012\Tundra.sln

Which built just fine. Just download master, unzip and run the above command line from within the *Visual C++ x64 Native Build Tools Command Prompt*.

Here's a link to the binaries

https://drive.google.com/open?id=0B5JWqqxHqeHeTXZvenRHZlVxalE

That's from my personal Google Drive so, it's might get throttled but it will work for now.

**Comment by leidegre** [comment]
Also, @deplinenoise I was under the impression that older versions of Visual Studio lacked the necessary C++11 features to actually compile tundra. Was I wrong?

**Comment by dyu** [comment]
Thanks for putting up the binaries @leidegre

**Comment by deplinenoise** [comment]
VS2012 is fine, and I expect 2015 to also work. At some point after the GDC craziness I'll put up an official windows build.

**Comment by deplinenoise** [comment]
Official binaries and installers are now available for 2.01.
